### ISSUE TITLE
Change App Name & Logo

### ISSUE THREAD

**Issue by mantreshkhurana** [mantreshkhurana/x-toxicity-detection-flask#11]
Since Twitter is now officially X, change Twitter to X in the project with the new logo.

**Comment by FazleRabbbiferdaus172** [comment]
hi there, looking for a contribution, Could you please assign me this one?

**Comment by FazleRabbbiferdaus172** [comment]
Hi, I have change the logo, 
Should I replace "Twitter" with "X" in the project?

**Comment by mantreshkhurana** [comment]
Yes, please use X's new logo as well with a good border-radius just like from the old Twitter logo used in this project.

**Comment by FazleRabbbiferdaus172** [comment]
@mantreshkhurana I have raised a PR, please have a look at your convenience.

**Comment by mantreshkhurana** [comment]
Sorry for a late reply, will look into it today.

**Comment by mantreshkhurana** [comment]
Can you please share screenshots of what it looks like since I am unable to test it right now.

**Comment by FazleRabbbiferdaus172** [comment]
Hi, I have added some screenshots of the new logo, homepage.

![image](https://github.com/mantreshkhurana/twitter-toxicity-detection-flask/assets/55714747/7709433f-6f2a-4638-85fa-ec8354b9e5eb)

![image](https://github.com/mantreshkhurana/twitter-toxicity-detection-flask/assets/55714747/a9a02346-89d0-43ea-ae34-7d8d61c7a23e)

![image](https://github.com/mantreshkhurana/twitter-toxicity-detection-flask/assets/55714747/bec1f73d-da3e-42eb-b069-b5df4f6c9251)

**Comment by mantreshkhurana** [comment]
Logo has been updated.
