### ISSUE TITLE
Fix CSS

### ISSUE THREAD

**Issue by mantreshkhurana** [mantreshkhurana/x-toxicity-detection-flask#2]
Since I built this project in very less time I had no time to lint some of the files like `style.css`, merge duplicates in css and create a pull request.

**Comment by Hendriksn** [comment]
I can do that. Would you please assign me? :)

**Comment by mantreshkhurana** [comment]
I have assigned you for this issue.

**Comment by Hendriksn** [comment]
I tried running the programm. Unfortunatly i get an error after searching for any user.

![image](https://user-images.githubusercontent.com/131691017/236615911-a6e0841b-c5d3-416d-a4e6-29dea42d04c8.png)

![image](https://user-images.githubusercontent.com/131691017/236615935-cdf82382-816d-4e4c-bbd1-f547805c9392.png)

How can i make it work?

**Comment by mantreshkhurana** [comment]
Please run and share screenshots:

```bash
which python
pip show tweepy
```

![Screenshot](https://user-images.githubusercontent.com/120998049/236616252-f09acfe7-61e3-43e4-9c39-20fc616d2f32.png)

**Comment by Hendriksn** [comment]
![image](https://user-images.githubusercontent.com/131691017/236616760-886773e4-321f-479c-bc2f-e6c32c0239b1.png)


![image](https://user-images.githubusercontent.com/131691017/236616723-4aff5ce2-6a83-4371-b3b3-89bb86e8efea.png)

**Comment by mantreshkhurana** [comment]
[TweepError was replaced with TweepyException](https://github.com/mantreshkhurana/twitter-toxicity-detection-flask/commit/0359bddf3b447f99d18be4c8e51b7b2f0cbc703a)

Since I was using an older version of Tweepy module `tweepy.TweepError` was deprecated and `TweepyException` replaced it.

I fixed it in the `stable` branch, please sync your forked repository.

> Note: Please share your project structure if it is still not working.

Example:

<img width="309" alt="Screenshot 2023-05-06 at 3 26 44 PM" src="https://user-images.githubusercontent.com/120998049/236617311-aa66d76a-58a8-464e-b597-67d9c27fb0bd.png">

**Comment by Hendriksn** [comment]
Now get this error: 
jinja2.exceptions.TemplateNotFound: error.html

![image](https://user-images.githubusercontent.com/131691017/236618059-5162bf7a-e27a-421c-8e24-f0791069d9a1.png)

**Comment by mantreshkhurana** [comment]
You are getting error due to API issues, please check your API credentials.

`error.html` is under development by another developer in a pull request right now this will load when you get a error due to `tweepy.TweepyException` since you are getting this error that means your API credentials are not properly written.

`.env` file should look like this with your [Twitter API credentials](https://developer.twitter.com/en/docs/twitter-api/getting-started/getting-access-to-the-twitter-api).

Example:

```env
CONSUMER_KEY=1234567890
CONSUMER_SECRET=1234567890
ACCESS_TOKEN=1234567890
ACCESS_TOKEN_SECRET=1234567890
```

**Comment by Hendriksn** [comment]
I got all the keys in my .env file.
If i got it right its: 
(On Consumer Keys)
CONSUMER_KEY = API Key
CONSUMER_SECRET = API Key Secret

(Authentication Tokens)
ACCESS_TOKEN = Access Token
ACCESS_TOKEN_SECRET = Access Token Secret

Im sorry for causing trouble, i just dont know how to fix this.

**Comment by mantreshkhurana** [comment]
Create a `error.html` in `templates/` directory. This may help for now. I need to create `error.html` asap to fix this error though. Gimme some time to fix this and push it.

**Comment by mantreshkhurana** [comment]
Hey @Hendriksn, I have added `error.html` which will show you the error you are getting. Please sync your forked repository.

Example:

In this example I edited my `.env` with wrong credentials to check if I will get any error or not, you need to restart your program to get the results properly(after fixing `.env`).

<img width="1624" alt="Screenshot 2023-05-06 at 8 27 20 PM" src="https://user-images.githubusercontent.com/120998049/236631782-1481c6eb-0ab1-43ca-bf7a-85cfefb9b35f.png">

**Comment by Hendriksn** [comment]
Thanks for fixing it!
Its just that my tokens on .env are invalide to the twitter api. I tried like 1000 times and copied the credentials from default projekt -> keys and tokens. It just doesn't want to accept me.  I guess you cannot do really much for me anymore. Im sorry man

https://user-images.githubusercontent.com/131691017/236633920-35c8b338-efff-4da1-88df-b8cc2745fa73.mp4

Or do i need to pay here for an "elevated" account lol

**Comment by mantreshkhurana** [comment]
Are you keeping the .env variables in quotes? 

Example:

API_KEY="abc"

Thank to for your time. No worries have a nice day.

**Comment by mantreshkhurana** [comment]
No need to pay for elevated account, thanks for your time, have a great journey ahead.

**Comment by mantreshkhurana** [comment]
Btw you can apply for elevated access for free, elevated access for 2M Tweets/month is free so feel free to apply for Twitter Elevated Access.

I need to provide this info in README too since Twitter started this with developer accounts.

[Updated README](https://github.com/mantreshkhurana/twitter-toxicity-detection-flask#installation)
