### ISSUE TITLE
Installing requirements.txt

### ISSUE THREAD

**Issue by BhuvanGarla** [mantreshkhurana/x-toxicity-detection-flask#7]
Many libraries are not installing pyQt 5.12 and many errors are coming while installing requirements.txt 
Please make video on how to run commands

**Comment by mantreshkhurana** [comment]
I will fix it asap.

**Comment by mantreshkhurana** [comment]
I fixed the `requirements.txt` file, please read [README.md | Installation](https://github.com/mantreshkhurana/twitter-toxicity-detection-flask#installation) section to setup your virtual environment and install modules easily.


https://github.com/mantreshkhurana/twitter-toxicity-detection-flask/assets/120998049/07c64a60-9c19-4909-8cb5-e6630675e283

**Comment by BhuvanGarla** [comment]
I am getting this error please help me

**Comment by mantreshkhurana** [comment]
What error are you getting? Can you please share a screenshot.

**Comment by BhuvanGarla** [comment]
I have shared screenshot

**Comment by mantreshkhurana** [comment]
Hey @BhuvanGarla, I can't see your screenshot. This is what I am able to see:

![IMG_6227](https://github.com/mantreshkhurana/twitter-toxicity-detection-flask/assets/120998049/c6ed2125-87dd-43c9-aab1-f76f10454ae1)

**Comment by mantreshkhurana** [comment]
I recommend opening a new issue if you are unable to upload screenshots, I can see your heading in the comments after the issue was reopened shows commented via email maybe this is causing issues, try to file a new issue.

**Comment by BhuvanGarla** [comment]
Can I get your personal email address
