### ISSUE TITLE
Twitter API Error

### ISSUE THREAD

**Issue by BhuvanGarla** [mantreshkhurana/x-toxicity-detection-flask#8]
![Screenshot_20230609_184317_Gallery](https://github.com/mantreshkhurana/twitter-toxicity-detection-flask/assets/119092965/97e279ea-7f4d-4259-9f84-fbfe936ca5ba)
![Screenshot_20230609_184353_Gallery](https://github.com/mantreshkhurana/twitter-toxicity-detection-flask/assets/119092965/e45dd92e-9d38-4547-bc39-316b860df340)

**Comment by mantreshkhurana** [comment]
So it is working, have you filled Twitter API keys correctly? If Yes, please follow these [steps](https://youtu.be/YtdGihjNn20) or follow steps from [README](https://github.com/mantreshkhurana/twitter-toxicity-detection-flask#installation), get Twitter elevated access, it is free for development category until your project consumes >20 Million tweets/month.

API keys should be stored in a file in the project folder named as `.env`. Checkout `.env.example` which is provided in the project for reference.

**Comment by mantreshkhurana** [comment]
Is it working? Do lemme know if it is working or not, I will be closing this issue in 48 hours.

**Comment by BhuvanGarla** [comment]
No Twitter basic is costing 100 dollars to get that api

**Comment by mantreshkhurana** [comment]
There is an option to sign up for free, register it and then follow https://youtu.be/YtdGihjNn20 this video to get elevated access. Twitter is now making it tougher to get API keys, please follow `Sign Up Free Account` and then get elevated access by following the video link from youtube I provided.

<img width="1512" alt="screenshot" src="https://github.com/mantreshkhurana/twitter-toxicity-detection-flask/assets/120998049/a1dc8340-bdc3-49bc-9fcd-80e210fd9af4">

**Comment by mantreshkhurana** [comment]
Hey @BhuvanGarla, please lemme know if it's working or not, if there is no easy way to get API access I will have to add a video on how to get API keys for free with elevated access.
