### ISSUE TITLE
ImportError: cannot import name 'url_quote' from 'werkzeug.urls'

### ISSUE THREAD

**Issue by sivaram-vinod** [mantreshkhurana/x-toxicity-detection-flask#9]
**Describe the bug**
 It is because Werkzeug 3.0.0 was released and Flask doesn't specify the dependency correctly (requirements says Werkzeug>=2.2.0). This is why, Werkzeug 3.0.0 is still installed and Flask 2.2.2 isn't made for Werkzeug 3.0.0

**To Reproduce**
1. Go to 'requirements.txt'
2. Add Werkzeug==2.2.2
3. Save.

**Expected behavior**
I fixed the issue using this, please fix it in another commit.

**Comment by rsk2** [comment]
I was interested in helping with this issue - but I can't find `url_quote` in the code base (stable branch). So, are these changes not required anymore or am I missing something?
